create extension if not exists pgcrypto;
create table public.products(sku text primary key, name text not null,image_path text not null,price_mad integer not null default 120 check(price_mad=120),active boolean not null default true,created_at timestamptz not null default now());
insert into public.products(sku,name,image_path) values ('CB301-SILVER','PRIMA SILVER','/products/optimized/prima-silver.webp'),('CB301-LED','PRIMA LED','/products/optimized/prima-led.webp'),('CB301-BLACK','PRIMA BLACK','/products/optimized/prima-black.webp');
create table public.store_settings(id integer primary key check(id=1),store_name text not null default 'WZNI',whatsapp_number text not null default '212783009072' check(whatsapp_number ~ '^212[67][0-9]{8}$'),delivery_city text not null default 'Marrakech' check(delivery_city='Marrakech'),delivery_fee_mad integer not null default 0 check(delivery_fee_mad=0),cod_enabled boolean not null default false,chatbot_enabled boolean not null default true,ai_chat_enabled boolean not null default false);
insert into public.store_settings(id) values(1);
create table public.orders(id uuid primary key default gen_random_uuid(),public_reference text not null unique default ('WZ-'||upper(encode(gen_random_bytes(6),'hex'))),idempotency_key uuid not null unique,customer_name text not null check(length(customer_name) between 2 and 100),customer_phone text not null check(customer_phone ~ '^\+212[67][0-9]{8}$'),district text not null,delivery_address text not null check(length(delivery_address) between 8 and 500),delivery_notes text,product_sku text not null references public.products(sku),quantity integer not null check(quantity between 1 and 20),unit_price_mad integer not null check(unit_price_mad=120),delivery_fee_mad integer not null check(delivery_fee_mad=0),total_mad integer not null check(total_mad=quantity*unit_price_mad+delivery_fee_mad),payment_method text not null check(payment_method in ('cash_on_delivery','to_confirm')),status text not null default 'new' check(status in ('new','confirmed','in_delivery','delivered','cancelled')),locale text not null check(locale in ('fr','ar')),utm_source text,utm_medium text,utm_campaign text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index orders_status_created on public.orders(status,created_at desc);
create index orders_product on public.orders(product_sku);
create function public.touch_order() returns trigger language plpgsql set search_path=public as $$begin new.updated_at=now();return new;end;$$;
create trigger orders_updated before update on public.orders for each row execute function public.touch_order();
create table public.faq_entries(id bigint generated always as identity primary key,question_fr text not null,answer_fr text not null,question_ar text not null,answer_ar text not null,active boolean not null default true);
create table public.rate_limits(bucket text primary key,hits integer not null,expires_at timestamptz not null);
create function public.consume_rate_limit(bucket_key text,max_hits integer,window_seconds integer) returns boolean language plpgsql security definer set search_path=public as $$declare count_hits integer;begin delete from rate_limits where expires_at<now()-interval '1 hour';insert into rate_limits(bucket,hits,expires_at) values(bucket_key,1,now()+make_interval(secs=>window_seconds)) on conflict(bucket) do update set hits=case when rate_limits.expires_at<now() then 1 else rate_limits.hits+1 end,expires_at=case when rate_limits.expires_at<now() then now()+make_interval(secs=>window_seconds) else rate_limits.expires_at end returning hits into count_hits;return count_hits<=max_hits;end;$$;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.store_settings enable row level security;
alter table public.faq_entries enable row level security;
alter table public.rate_limits enable row level security;
revoke all on public.orders,public.rate_limits,public.store_settings,public.faq_entries,public.products from anon,authenticated;
grant all on public.orders,public.rate_limits,public.store_settings,public.faq_entries,public.products to service_role;
grant usage,select on all sequences in schema public to service_role;
revoke all on function public.consume_rate_limit(text,integer,integer) from public,anon,authenticated;
grant execute on function public.consume_rate_limit(text,integer,integer) to service_role;
